env:
  browser: true
  es6: true
  'jest/globals': true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
  - 'prettier/react'
parser: 'babel-eslint'
plugins:
  - prettier
  - jest
  - react
rules:
  'prettier/prettier': error
  indent:
    - error
    - 2
    - SwitchCase: 1

  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-warning-comments:
    - warn
    - terms:
        - todo
        - fixme
      location: anywhere
